default: &default
  subreddit: "xxanime"
  scoring:
    mean: 6.55 # A mean to weight the scores towards
    minimum: 3.0 # The minimum number of scores before something can be ranked.

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
